#!/bin/bash
#make -j
./wait-for ${DB_HOST}:${DB_PORT} -t 0
./wait-for ${DATABASE_HOST}:${REST_PORT} -t 0
./wait-for ${PREFIXTREE_HOST}:${REST_PORT} -t 0
./wait-for ${CONFIGURATION_HOST}:${REST_PORT} -t 0
./wait-for ${FILEOBSERVER_HOST}:${REST_PORT} -t 0
./wait-for ${RIPERISTAP_HOST}:${REST_PORT} -t 0
# TODO: use translated cython files instead of the scripts themselves
/usr/local/bin/python /root/core/autostarter.py
