#!/bin/bash
#make -j
./wait-for ${DB_HOST}:${DB_PORT} -t 0
./wait-for database:3000 -t 0
./wait-for prefixtree:3000 -t 0
./wait-for configuration:3000 -t 0
./wait-for fileobserver:3000 -t 0
# TODO: use translated cython files instead of the scripts themselves
/usr/local/bin/python /root/core/autostarter.py
