#!/bin/bash
./wait-for rabbitmq:5672 -t 60
./wait-for postgres:5432 -t 60
./wait-for postgrest:3000 -t 60
#./wait-for syslog:514 -t 60
# TODO: find better solution!
sleep 30
gunicorn --workers=4 --bind 0.0.0.0:8000 webapp_init:app
