#!/bin/bash
./wait-for ${RABBITMQ_HOST}:${RABBITMQ_PORT} -t 0
./wait-for ${DB_HOST}:${DB_PORT} -t 0
./wait-for ${API_HOST}:${API_PORT} -t 0
./wait-for ${HASURA_HOST}:${HASURA_PORT} -t 0
./wait-for database:${REST_PORT} -t 0
PATH="/usr/local/lib/pyenv/versions/${PYTHON_VERSION}/bin/:${PATH}" gunicorn --workers=${GUNICORN_WORKERS:-4} --bind 0.0.0.0:8000 --preload init:app
