prefixes:
    8_prefix: &8_prefix
        - 10.0.0.0/8
    16_prefix: &16_prefix
        - 10.0.0.0/16
monitors:
    riperis: []
asns:
    8_origin: &8_origin
        1
    8_upstream: &8_upstream
        2
rules:
- prefixes:
  - *8_prefix
  origin_asns:
  - *8_origin
  neighbors:
  - *8_upstream
  mitigation:
      manual
- prefixes:
  - *16_prefix
  mitigation:
      manual
