prefixes:
    8_prefix: &8_prefix
        - 10.0.0.0/8
    16_prefix: &16_prefix
        - 10.0.0.0/16
    24_prefix_1: &24_prefix_1
        - 10.0.1.0/24
    24_prefix_2: &24_prefix_2
        - 10.0.2.0/24
    24_prefix_3: &24_prefix_3
        - 10.0.3.0/24
monitors:
    riperis: []
asns:
    8_origin: &8_origin
        1
    8_upstream: &8_upstream
        2
    24_2_origin: &24_2_origin
        242
    24_3_origin: &24_3_origin
        243
rules:
- prefixes:
  - *8_prefix
  origin_asns:
  - *8_origin
  neighbors:
  - *8_upstream
  mitigation:
      manual
- prefixes:
  - *16_prefix
  mitigation:
      manual
- prefixes:
  - *24_prefix_1
  origin_asns:
      '*'
  mitigation:
      manual
- prefixes:
  - *24_prefix_2
  origin_asns:
  - *24_2_origin
  mitigation:
      manual
- prefixes:
  - *24_prefix_3
  origin_asns:
  - *24_3_origin
  neighbors:
      '*'
  mitigation:
      manual
