version: '3'
services:
    exabgp:
        image: mavromat/exabgp-monitor:latest
        container_name: exabgp
        restart: always
        networks:
            - artemis
        volumes:
            # comment after Step 2 of README
            - ./monitor/configs/exabgp.conf:/home/config/exabgp.conf
            # uncomment after Step 2 of README
            # - ./local_configs/monitor/exabgp.conf:/home/config/exabgp.conf
