#!/bin/bash
make
./wait-for rabbitmq:5672 -t 60
./wait-for postgres:5432 -t 60
#./wait-for syslog:514 -t 60
service cron start
# service supervisor start
# supervisorctl
redis-server /etc/redis/redis.conf --daemonize yes
supervisord -n
