apiVersion: v1
items:
{{- range .Values.services }}
-   apiVersion: v1
    kind: Service
    metadata:
    annotations:
        kompose.cmd: kompose convert -c --volumes hostPath -f docker-compose.yaml -o helm
        kompose.service.type: headless
        kompose.version: 1.18.0 (HEAD)
    creationTimestamp: null
    labels:
        io.kompose.service: {{ . | quote }}
    name: {{ . | quote }}
    spec:
    clusterIP: None
    ports:
    - name: headless
        port: 55555
        targetPort: 0
    selector:
        io.kompose.service: {{ . | quote }}
    status:
    loadBalancer: {}
{{- end }}
