apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath -f docker-compose.yaml -o helm
    kompose.service.type: headless
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pg-amqp-bridge
  name: pg-amqp-bridge
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pg-amqp-bridge
    spec:
      containers:
      - args:
        - /root/wait-for
        - {{ .Values.rabbitmqHost }}:{{ .Values.rabbitmqPort }}
        - -t
        - "0"
        - --
        - pg-amqp-bridge
        env:
        - name: AMQP_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dbUri
        - name: BRIDGE_CHANNELS
          value: events:amq.direct
        - name: POSTGRESQL_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dbUri
        image: subzerocloud/pg-amqp-bridge:0.0.6
        name: pg-amqp-bridge
        resources: {}
        volumeMounts:
        - mountPath: /root/wait-for
          name: pg-amqp-bridge-configmap0
          subPath: wait-for
      restartPolicy: Always
      volumes:
      - configMap:
          name: {{ .Release.Name }}-volumes
          defaultMode: 0777
        name: pg-amqp-bridge-configmap0
status: {}
