apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath -f docker-compose.yaml -o helm
    kompose.service.type: headless
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pg-amqp-bridge
  name: pg-amqp-bridge
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pg-amqp-bridge
    spec:
      containers:
      - args:
        - /root/wait-for
        - rabbitmq:5672
        - -t
        - "0"
        - --
        - pg-amqp-bridge
        env:
        - name: AMQP_URI
          value: amqp://guest:guest@rabbitmq:5672//
        - name: BRIDGE_CHANNELS
          value: events:amq.direct
        - name: POSTGRESQL_URI
          value: postgres://artemis_user:Art3m1s@postgres:5432/artemis_db
        image: subzerocloud/pg-amqp-bridge:0.0.6
        name: pg-amqp-bridge
        resources: {}
        volumeMounts:
        - mountPath: /root/wait-for
          name: pg-amqp-bridge-hostpath0
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/dimitris/github/artemis/backend/wait-for
        name: pg-amqp-bridge-hostpath0
status: {}
