apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath -f docker-compose.yaml -o helm
    kompose.service.type: headless
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: postgrest
  name: postgrest
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgrest
    spec:
      containers:
      - env:
        - name: PGRST_DB_ANON_ROLE
          value: artemis_user
        - name: PGRST_DB_SCHEMA
          value: public
        - name: PGRST_DB_URI
          value: postgres://artemis_user:Art3m1s@postgres:5432/artemis_db
        image: postgrest/postgrest:v5.2.0
        name: postgrest
        resources: {}
      restartPolicy: Always
status: {}
