apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  hasuraSecret: {{ .Values.hasuraSecret | b64enc }}
  jwtSecret: {{ .Values.jwtSecret | b64enc }}
  flaskSecret: {{ .Values.flaskSecret | b64enc }}
  passwordSalt: {{ .Values.passwordSalt | b64enc }}
