apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-volumes
  labels:
    app: {{ .Release.Name }}
data:
  {{- (.Files.Glob "files/configmaps/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-volumes
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- (.Files.Glob "files/secrets/*").AsSecrets | nindent 2 }}
