prefixes:
    super_prefix: &super_prefix
        - 139.91.0.0/16
    sub_prefix_1: &sub_prefix_1
        139.91.250.0/24
    sub_prefix_2: &sub_prefix_2
        139.91.2.0/24
    sub_prefix_3: &sub_prefix_3
        10.1.0.0/24

asns:
    my_asn: &my_asn
        8522
    primary_upstream: &primary_upstream
        5408
    backup_upstream_1: &backup_upstream_1
        56910
    backup_upstream_2: &backup_upstream_2
        12361

rules:
- prefixes:
    - *super_prefix
  origin_asns:
    - *my_asn
  neighbors:
    - *primary_upstream
    - *backup_upstream_1
    - *backup_upstream_2
  mitigation:
      manual
- prefixes:
    - *sub_prefix_1
  origin_asns:
    - *my_asn
  neighbors:
    - *backup_upstream_1
  mitigation:
    manual
- prefixes:
    - *sub_prefix_2
  origin_asns:
    - *my_asn
  neighbors:
    - *backup_upstream_2
  mitigation:
    manual
- prefixes:
    - *sub_prefix_3
  mitigation:
    manual
