#!/bin/bash

pip --no-cache-dir install coverage git+https://github.com/coveralls-clients/coveralls-python@a9b5e3081c8697b60286b9736e956134a2796d5f

./wait-for ${RABBITMQ_HOST}:${RABBITMQ_PORT} -t 0
./wait-for ${DB_HOST}:${DB_PORT} -t 0
./wait-for ${BACKEND_SUPERVISOR_HOST}:${BACKEND_SUPERVISOR_PORT} -t 0

python -u tester.py
