# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_BOX = "ubuntu/bionic64"
VM_NAME = 'artemis-vm'

Vagrant.configure(2) do |config|

  # Configure VM
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VM_NAME
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.cpus = 4
    v.memory = 4096
    v.gui = true
  end

  # Install ARTEMIS dependencies (provisioning)
  config.vm.provision "shell", path: "bootstrap.sh"

  # Instruct ARTEMIS to always use latest containers
  config.vm.provision :shell, :inline => "cd artemis && git pull origin master && docker-compose pull && docker-compose up -d", run: "always"
end
