# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protogrpc.hservice_pb2 as hservice__pb2


class MessageListenerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.queryHformat = channel.unary_unary(
        '/hservice.MessageListener/queryHformat',
        request_serializer=hservice__pb2.HformatMessage.SerializeToString,
        response_deserializer=hservice__pb2.Empty.FromString,
        )


class MessageListenerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def queryHformat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageListenerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'queryHformat': grpc.unary_unary_rpc_method_handler(
          servicer.queryHformat,
          request_deserializer=hservice__pb2.HformatMessage.FromString,
          response_serializer=hservice__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hservice.MessageListener', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
