# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protogrpc.mservice_pb2 as mservice__pb2


class MessageListenerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.queryMformat = channel.unary_unary(
        '/mservice.MessageListener/queryMformat',
        request_serializer=mservice__pb2.MformatMessage.SerializeToString,
        response_deserializer=mservice__pb2.Empty.FromString,
        )


class MessageListenerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def queryMformat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageListenerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'queryMformat': grpc.unary_unary_rpc_method_handler(
          servicer.queryMformat,
          request_deserializer=mservice__pb2.MformatMessage.FromString,
          response_serializer=mservice__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mservice.MessageListener', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
