{
 "title": "Artemis::BGP Updates per prefix",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "prefix",
    "query": "SELECT distinct(prefix) from bgp_updates WHERE $__timeFilter(\"timestamp\")"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total BGP Updates",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from \"timestamp\")) AS \"time\",\n  prefix AS metric,\n  count(key) as \"update\"\nFROM bgp_updates\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  prefix in ($prefix)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Total BGP - Announcements",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 8, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from \"timestamp\")) AS \"time\",\n  prefix AS metric,\n  count(key) as \"update\"\nFROM bgp_updates\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  prefix in ($prefix) AND type = 'A'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Total BGP - Withdrawals",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from \"timestamp\")) AS \"time\",\n  prefix AS metric,\n  count(key) as \"update\"\nFROM bgp_updates\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  prefix in ($prefix) AND type = 'W'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Prefix - $prefix",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "repeat": "prefix",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  CONCAT(prefix,':',type) AS metric,\n  count(key) AS \"add\"\nFROM bgp_updates\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  prefix IN ($prefix)\nGROUP BY 1, type,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}