{
 "title": "Artemis::BGP Updates per service",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total BGP Updates",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from \"timestamp\")) AS \"time\",\n  service AS metric,\n  count(key) as \"update\"\nFROM bgp_updates\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Withdrawals",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from \"timestamp\")) AS \"time\",\n  service AS metric,\n  count(*) as \"update\"\nFROM bgp_updates\nWHERE\n  $__timeFilter(\"timestamp\") AND type = 'W'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Adds",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from \"timestamp\")) AS \"time\",\n  service AS metric,\n  count(*) as \"update\"\nFROM bgp_updates\nWHERE\n  $__timeFilter(\"timestamp\") AND type = 'A'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}