{
 "title": "Artemis::Offending ASes",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hijack_as",
    "query": "SELECT distinct(hijack_as) from hijacks WHERE  $__timeFilter(time_detected)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top offending ASes -  Active",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_detected,$__interval),\n  concat('AS', hijack_as) AS metric,\n  count(*) AS \"hijack\"\nFROM hijacks\nWHERE\n  $__timeFilter(time_detected) AND\n  hijack_as IN ($hijack_as) and active = true\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Top offending ASes -  Non-Active",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_detected,$__interval),\n  concat('AS', hijack_as) AS metric,\n  count(*) AS \"hijack\"\nFROM hijacks\nWHERE\n  $__timeFilter(time_detected) AND\n  hijack_as IN ($hijack_as) and active = false\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "AS - $hijack_as",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "repeat": "hijack_as",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_detected,$__interval),\n  CONCAT(hijack_as, '  (', type,')', 'active:', active) AS metric,\n  count(*) AS \"hijack_as\"\nFROM hijacks\nWHERE\n  $__timeFilter(time_detected) AND\n  hijack_as IN ($hijack_as)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}