version: '3'
services:
  pocdeaggregator:
    build:
      dockerfile: Dockerfile
      context: ./dockers/pocdeaggregator
    container_name: pocdeaggregator
    restart: always
    depends_on:
      - exabgp
      - r02
      - r03
    networks:
      comm:
        ipv4_address: 1.1.1.11
  exabgp:
    image: mavromat/exabgp-monitor:latest
    container_name: exabgp
    restart: always
    networks:
      comm:
        ipv4_address: 1.1.1.10
    volumes:
      - ./configs/exabgp/exabgp.conf:/home/config/exabgp.conf
  r02:
    image: gobgp:latest
    build:
      dockerfile: Dockerfile
      context: ./dockers/gobgp
    container_name: r02
    restart: always
    networks:
      comm:
        ipv4_address: 1.1.1.2
    volumes:
      - ./configs/gobgp/r02.conf:/etc/gobgp/gobgp.conf
  r03:
    image: gobgp:latest
    build:
      dockerfile: Dockerfile
      context: ./dockers/gobgp
    container_name: r03
    restart: always
    networks:
      comm:
        ipv4_address: 1.1.1.3
    volumes:
      - ./configs/gobgp/r03.conf:/etc/gobgp/gobgp.conf

networks:
  comm:
    ipam:
      driver: default
      config:
        - subnet: 1.1.1.0/24
