version: '3'
services:
  pocdeaggregator:
    build:
      dockerfile: Dockerfile
      context: ./dockers/pocdeaggregator
    container_name: pocdeaggregator
    restart: always
    depends_on:
      - exabgpmitigate
      - r02
      - r03
    networks:
      comm:
        ipv4_address: 1.1.1.11
    volumes:
      - ./dockers/pocdeaggregator/init.py:/root/init.py
      - ./dockers/pocdeaggregator/poc_mitigate_deaggregate.py:/root/poc_mitigate_deaggregate.py
      - ./configs/exabgp/exa_mitigation_commands.json:/root/exa_mitigation_commands.json
  exabgpmitigate:
    image: mavromat/exabgp-monitor:latest
    container_name: exabgpmitigate
    restart: always
    networks:
      comm:
        ipv4_address: 1.1.1.10
    volumes:
      - ./configs/exabgp/exabgp.conf:/home/config/exabgp.conf
      - ./configs/exabgp/exa_mitigation_commands.json:/home/config/exa_mitigation_commands.json
      - ./configs/exabgp/exa_bgp_send.py:/opt/exabgp/run/exa_bgp_send.py
  r02:
    image: gobgp:latest
    build:
      dockerfile: Dockerfile
      context: ./dockers/gobgp
    container_name: r02
    restart: always
    networks:
      comm:
        ipv4_address: 1.1.1.2
    volumes:
      - ./configs/gobgp/r02.conf:/etc/gobgp/gobgp.conf
  r03:
    image: gobgp:latest
    build:
      dockerfile: Dockerfile
      context: ./dockers/gobgp
    container_name: r03
    restart: always
    networks:
      comm:
        ipv4_address: 1.1.1.3
    volumes:
      - ./configs/gobgp/r03.conf:/etc/gobgp/gobgp.conf

networks:
  comm:
    ipam:
      driver: default
      config:
        - subnet: 1.1.1.0/24
