{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --controller deployment --volumes hostPath -f docker-compose.yaml -o k8s.yaml
    kompose.service.type: headless
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ . }}
  name: {{ . }}
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: {{ . }}
status:
  loadBalancer: {}
---
{{- end }}
