{{- if not .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
    app: {{ .Release.Name }}
  name: nginx
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox
        command: ['sh', '-c', 'until nc -z {{ .Values.webappHost }} {{ .Values.webappPort }} && nc -z {{ .Values.hasuraHost }} {{ .Values.hasuraPort }}; do echo waiting for services; sleep 10; done;']
      containers:
      - image: nginx:1.15-alpine
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-configmap0
          subPath: nginx.conf
        - mountPath: /etc/nginx/certs/
          name: nginx-secret0
      restartPolicy: Always
      volumes:
      - configMap:
          name: {{ .Release.Name }}-volumes
        name: nginx-configmap0
      - secret:
          secretName: {{ .Release.Name }}-secret-tls
          items:
          - key: tls.crt
            path: cert.pem
          - key: tls.key
            path: key.pem
        name: nginx-secret0
status: {}
{{- end -}}
