{{- if not .Values.ingress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nginx
  name: {{ .Release.Name }}-nginx
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
{{- end -}}
