apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  hasuraSecret: {{ required "A valid .Values.hasuraSecret entry required!" .Values.hasuraSecret | b64enc }}
  jwtSecret: {{ required "A valid .Values.jwtSecret entry required!" .Values.jwtSecret | b64enc }}
  flaskSecret: {{ required "A valid .Values.flaskSecret entry required!" .Values.flaskSecret | b64enc }}
  passwordSalt: {{ required "A valid .Values.passwordSalt entry required!" .Values.passwordSalt | b64enc }}
  hasuraJwt: {{ (printf "{\"type\":\"HS256\", \"key\":\"%s\" }" .Values.jwtSecret) | b64enc  }}
  dbPass: {{ .Values.dbPass | default "Art3m1s" | b64enc }}
  adminPass: {{ .Values.adminPass | default "admin123" | b64enc }}
  rabbitmqPass: {{ .Values.rabbitmqPass | default "guest" | b64enc }}
---
{{- if or (not .Values.ingress.enabled) (.Values.ingress.tlsEnabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-tls
  labels:
    app: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "A valid .Values.certificate entry required!" .Values.certificate | b64enc }}
  tls.key: {{ required "A valid .Values.privKey entry required!" .Values.privKey | b64enc }}
{{- end -}}
