apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  hasuraSecret: {{ required "A valid .Values.hasuraSecret entry required!" .Values.hasuraSecret | b64enc }}
  jwtSecret: {{ required "A valid .Values.jwtSecret entry required!" .Values.jwtSecret | b64enc }}
  flaskSecret: {{ required "A valid .Values.flaskSecret entry required!" .Values.flaskSecret | b64enc }}
  passwordSalt: {{ required "A valid .Values.passwordSalt entry required!" .Values.passwordSalt | b64enc }}
