apiVersion: v1
kind: Secret
metadata:
  name: secret
  labels:
{{ include "artemis.labels" . | indent 4 }}
type: Opaque
data:
  hasuraSecret: {{ required "A valid .Values.hasuraSecret entry required!" .Values.hasuraSecret | b64enc }}
  jwtSecret: {{ required "A valid .Values.jwtSecret entry required!" .Values.jwtSecret | b64enc }}
  dbPass: {{ .Values.dbPass | default "Art3m1s" | b64enc }}
  mongodbPass: {{ .Values.mongodbPass | default "pass" | b64enc }}
  adminPass: {{ .Values.adminPass | default "admin1234" | b64enc }}
  rabbitmqPass: {{ .Values.rabbitmqPass | default "guest" | b64enc }}
  hasuraJwt: {{ .Values.jwtSecret | b64enc }}
---
{{- if or (not .Values.ingress.enabled) (.Values.ingress.tlsEnabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  labels:
{{ include "artemis.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "A valid .Values.certificate entry required!" .Values.certificate | b64enc }}
  tls.key: {{ required "A valid .Values.privKey entry required!" .Values.privKey | b64enc }}
{{- end -}}
