apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-volumes
  labels:
{{ include "artemis.labels" . | indent 4 }}
data:
  {{- (.Files.Glob "files/configmaps/*").AsConfig | nindent 2 }}
