#!/bin/bash

./wait-for ${RABBITMQ_HOST}:${RABBITMQ_PORT} -t 0
./wait-for ${DB_HOST}:${DB_PORT} -t 0
./wait-for ${SUPERVISOR_HOST}:${SUPERVISOR_PORT} -t 0
./wait-for ${REDIS_HOST}:${REDIS_PORT} -t 0

python -u tester.py
