#!/bin/bash
#make -j
./wait-for ${RABBITMQ_HOST}:${RABBITMQ_PORT} -t 0
# TODO: remove this after correct artemis-utils release
pip install -e /root/utils
# TODO: use translated cython files instead of the scripts themselves
/usr/local/bin/python /root/core/notifier.py
