#!/bin/bash
make -j
./wait-for ${RABBITMQ_HOST}:${RABBITMQ_PORT} -t 0
./wait-for ${REDIS_HOST}:${REDIS_PORT} -t 0
# should wait for the following services so that it configures them when up
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)database:${REST_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)prefixtree:${REST_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)riperistap:${REST_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)bgpstreamlivetap:${REST_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)bgpstreamkafkatap:${REST_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)bgpstreamhisttap:${REST_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)exabgptap:${REST_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)detection:${REST_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)mitigation:${REST_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)notifier:${REST_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)autoignore:${REST_PORT} -t 0

cd ./core
/usr/local/bin/python -c "import configuration; configuration.main()"
