# general
guiEnabled: true
systemVersion: latest
historic: false
# headless services
services:
    - backend
    - postgrest
    - postgres
    - frontend
    - rabbitmq
    - graphql
# redis
redisHost: backend
redisPort: 6379
# supervisor
supervisorHost: backend
supervisorPort: 9001
# api
apiHost: postgrest
apiPort: 3000
# database
dbHost: postgres
dbPort: 5432
dbVersion: 12
dbName: artemis_db
dbUser: artemis_user
dbPass: Art3n1s
dbSchema: public
dbAutoClean: false
dbBackup: true
dbHijackDormant: false
# webapp
bindIp: 0.0.0.0
webappHost: frontend
webappPort: 8000
adminUser: admin
adminPass: admin123
adminEmail: admin@admin
jsVersion: 0.1.2
# rabbitmq
rabbitmqHost: rabbitmq
rabbitmqPort: 5672
rabbitmqUser: guest
rabbitmqPass: guest
# hasura
hasuraHost: graphql
hasuraPort: 8080
hasuraGui: false
# secret keys
hasuraSecret: "@rt3m1s."
jwtSecret: 44fe431cdc896ccab691ad0599f4e0a12690ce1ededebe57b825823bc6b4d24f
flaskSecret: 76f8bae45e807865955344c1a58882d38c8ceb4f855f58091642b7d48290af97
passwordSalt: 06a4b397fc7045eac527c2aec3ff46cee5ce30016c760f238c26e79902fe67b6
