#!/bin/bash
make -j
./wait-for ${RABBITMQ_HOST}:${RABBITMQ_PORT} -t 0
./wait-for ${REDIS_HOST}:${REDIS_PORT} -t 0
./wait-for $(if [[ ! -z "${RELEASE_NAME}" ]]; then echo ${RELEASE_NAME}-; fi)prefixtree:${REST_PORT} -t 0

cd ./core
/usr/local/bin/python -c "import bgpstreamlive; bgpstreamlive.main()"
