#!/bin/bash

./wait-for ${RABBITMQ_HOST}:${RABBITMQ_PORT} -t 0
./wait-for ${DB_HOST}:${DB_PORT} -t 0
./wait-for configuration:3000 -t 0
./wait-for database:3000 -t 0
./wait-for detection:3000 -t 0
./wait-for fileobserver:3000 -t 0
./wait-for prefixtree:3000 -t 0

python -u tester.py
